// src/lib/games-config.ts
import {
  Gamepad2,
  Scissors,
  Sword,
  Ghost,
  Zap,
  Target,
  BoxSelect,
  MonitorPlay,
  Bomb,
  Brain,
  LayoutGrid,
} from "lucide-react";

export const ALL_GAMES = [
  {
    name: "Tic-Tac-Toe",
    path: "/tic-tac-toe",
    icon: Gamepad2,
    color: "text-blue-500",
    category: "Classic",
  },
  {
    name: "Rock Paper Scissors",
    path: "/rock-paper-scissors",
    icon: Scissors,
    color: "text-red-500",
    category: "Classic",
  },
  {
    name: "Chess Arena",
    path: "/chess",
    icon: Sword,
    color: "text-orange-500",
    category: "Strategy",
  },
  {
    name: "Pac-Man",
    path: "/pac-man",
    icon: Ghost,
    color: "text-yellow-400",
    category: "Arcade",
  },
  {
    name: "Snake",
    path: "/snake",
    icon: Zap,
    color: "text-green-500",
    category: "Arcade",
  },
  {
    name: "Connect Four",
    path: "/connect-four",
    icon: Target,
    color: "text-red-600",
    category: "Strategy",
  },
  {
    name: "Tetris",
    path: "/tetris",
    icon: BoxSelect,
    color: "text-purple-500",
    category: "Puzzle",
  },
  {
    name: "Pong",
    path: "/pong",
    icon: MonitorPlay,
    color: "text-slate-400",
    category: "Arcade",
  },
  {
    name: "Minesweeper",
    path: "/minesweeper",
    icon: Bomb,
    color: "text-gray-500",
    category: "Puzzle",
  },
  {
    name: "Memory Match",
    path: "/memory-match",
    icon: Brain,
    color: "text-pink-500",
    category: "Logic",
  },
  {
    name: "Sudoku",
    path: "/sudoku",
    icon: LayoutGrid,
    color: "text-cyan-500",
    category: "Logic",
  },
];
